export const cities: any = {
	"balneário camboriú": "balneario_camboriu",
	"balneário piçarras": "picarras",
	"barra velha": "barra_velha",
	"bombinhas": "bombinhas",
	"blumenau": "blumenau",
	"brusque": "brusque",
	"chapecó": "chapeco",
	"camboriú": "camboriu",
	"criciúma": "criciuma",
	"gaspar": "gaspar",
	"indaial": "indaial",
	"joinville": "joinville",
	"florianópolis": "florianopolis",
	"itajaí": "itajai",
	"itapema": "itapema",
	"jaraguá do sul": "jaragua_do_sul",
	"navegantes": "navegantes",
	"palhoça": "palhoca",
	"penha": "penha",
	"portobelo": "portobelo",
	"rio do sul": "rio_do_sul",
	"são josé": "sao_jose",
	"tijucas": "tijucas",
	"timbó": "timbo",
}