export const data: any = {
	"balneario_camboriu": 28,
	"barra_velha": 32,
	"blumenau": 37,
	"bombinhas": 43,
	"brusque": 48,
	"camboriu": 52,
	"chapeco": 67,
	"criciuma": 75,
	"florianopolis": 88,
	"gaspar": 96,
	"indaial": 114,
	"itajai": 126,
	"itapema": 127,
	"jaragua_do_sul": 134,
	"joinville": 137,
	"navegantes": 169,
	"palhoca": 181,
	"penha": 191,
	"picarras": 194,
	"porto_belo": 203,
	"rio_do_sul": 216,
	"sao_jose": 248,
	"tijucas": 267,
	"timbo": 269,
}

export const cities: any = {
	"balneário camboriú": "balneario_camboriu",
	"balneário piçarras": "picarras",
	"barra velha": "barra_velha",
	"bombinhas": "bombinhas",
	"blumenau": "blumenau",
	"brusque": "brusque",
	"chapecó": "chapeco",
	"camboriú": "camboriu",
	"criciúma": "criciuma",
	"gaspar": "gaspar",
	"indaial": "indaial",
	"joinville": "joinville",
	"florianópolis": "florianopolis",
	"itajaí": "itajai",
	"itapema": "itapema",
	"jaraguá do sul": "jaragua_do_sul",
	"navegantes": "navegantes",
	"palhoça": "palhoca",
	"penha": "penha",
	"porto belo": "porto_belo",
	"rio do sul": "rio_do_sul",
	"são josé": "sao_jose",
	"tijucas": "tijucas",
	"timbó": "timbo",
}